### ISSUE TITLE
Would it be possible to allow capacity to be Float64 instead of Int? 

### ISSUE THREAD

**Issue by juliebuard** [NREL/PRASBase.jl#7]
https://github.com/NREL/PRASBase.jl/blob/80ad2e1ca6435567924742d54a0d3a7a0fb0b16e/src/assets.jl#L9

Would allowing capacity to be `capacity::Matrix{Float64}` lead to some numerical issue later on or would that be possible to be changed in the struct definition? 
Same with load in system definition?

**Comment by GordStephen** [comment]
Both the convolution in `Classic` and the min cost flow problem in `Modern` round capacities and load to the nearest integer anyways, so the idea here was to make that rounding more transparent. If you need more resolution, one option would be to define the problem in terms of different units (e.g. kW instead of MW), although the relevant conversion functions would need to be defined (not too difficult): https://github.com/NREL/PRASBase.jl/blob/80ad2e1ca6435567924742d54a0d3a7a0fb0b16e/src/units.jl#L39-L43

**Comment by juliebuard** [comment]
Great! Thank you this would work indeed and having the transparency about rounding up if the unit system chosen is MW is indeed very relevant!

**Comment by GordStephen** [comment]
Ok, great. 3c77fa5ff970c9c4f52166ed86ea6d57b9dce3a9 added better unit conversion support and should get merged into `master` soon.
